name: Ejecutar código Python diariamente

# Definir cuándo se ejecutará la acción (cron expression para todos los días a las 12:00 UTC)

#on:
 # schedule:
  #  - cron: '0 12 * * *'  # Todos los días a las 12:00 UTC
on:
  push:
    branches: [main]
# Definir los jobs
jobs:
  run-python-script: # build
    runs-on: ubuntu-latest  # Usaremos una máquina con Ubuntu

    permissions:
      contents: write
      
    steps:
      # Primer paso: Checkout (obtener el código del repositorio)
      - name: Checkout repository
        uses: actions/checkout@v4

      # Segundo paso: Configurar Python (versión 3.11, puedes cambiarla si lo necesitas)
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      # Tercer paso: Instalar las dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests matplotlib streamlit

      # Cuarto paso: Ejecutar el script de Python
      - name: Run Python script
        run: |
          python ./app.py

      # Quinto paso: Commit y push si la gráfica fue modificada
      - name: Commit and Push
        run: |
          git config --global user.name 'JTL - GitHub Actions'
          git config --global user.email 'jaterli@hotmail.com'
          git add grap.png
          git commit -m "Updated graph"
          git push
        if: success()  # Solo hacer commit si el script se ejecuta correctamente
